[package]
	edition = "2021"
	name    = "euler-005"
	version = "0.0.0"

	# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
	name = "5"
	path = "src/main.rs"

[dependencies]
	euler-utils = { path = "../euler-utils" }
